---
- name: IOS Upgrade Process - Verify
  hosts: all
  gather_facts: no
  
  tasks:
 
# Find out Current Version and Uptime on Router
    - name: IOS Version
      ios_command:
       commands: "show version | i Version"
      register: version_result  
     
	   commands: "show version | i Uptime"
      register: uptime_result  
    
	- name: show ver output
      debug: var=version_result.stdout_lines
	  
	- name: show uptime output
      debug: var=uptime_result.stdout_lines
 
    
     
    
     
# Find out Current Boot Marker on Router    
    - name: show boot marker
      ios_command:
       commands: "show run | sec boot"
      register: boot_result  
     
    - name: show ver output
      debug: var=boot_result.stdout_lines
  
# Difference between Saved and Running Config   
    - name: verify config change
      ios_command:
       commands: "show arc config diff"
      register: config_diff_result  
    
    - name: show config diff output
      debug: var=config_diff_result.stdout_lines
     
# Write Config 
    - name: write config
      ios_command:
       commands: 
         - command: "wr"
         
# Reload Device         
    - name: Reloading Device
      ios_command:
		commands: 
         - command: "reload\n"
           prompt: 'Proceed with reload? [confirm]'
           answer: "\r"
		   
#  Waiting for COnnection to Recur 
	- name: Wait for the network device to reload
	  wait_for_connection:
		delay: 10
    
    
# Find out Current Version and Uptime on Router
    - name: IOS Version
      ios_command:
       commands: "show version | i Version"
      register: version_result1  
     
	   commands: "show version | i Uptime"
      register: uptime_result1  
    
	- name: show ver output
      debug: var=version_result1.stdout_lines
	  
	- name: show uptime output
      debug: var=uptime_result1.stdout_lines
 
    
     
