---
- name: IOS Upgrade
  hosts: all
  gather_facts: no

 tasks:
  - name: Show inventory
    ios_command:
      commands: "show inventory"
    register: result
      
  - name: Display output
    debug: var=result.stdout_line
