---
- name: IOS Upgrade
  hosts: all
  gather_facts: no

  vars:
    ios_version: "{{ ios_version }}"
    ios_filename: "{{ ios_filename }}"

  tasks:
    - name: Verify IOS version on device
      ios_facts:
