- name: test
  hosts: all
  gather_facts: no

  tasks:
    - name: show module and ip interfaces brief
      ios_command:
        commands:
            - show module
            - show ip interface brief
