---
- name: IOS Upgrade Process - Verify
  hosts: all
  gather_facts: no
  
  tasks:
   - name: show ver
     ios_command:
       commands: "show version | i Version"
     register: version_result  
     debug: var=version_result.stdout_lines
    
   - name: show boot marker
     ios_command:
      commands: "show run | sec boot"
     register: boot_result  
     debug: var=boot_result.stdout_lines
    

    
    
