---
- name: Show Version on IOS
  hosts: all
  gather_facts: no
  
  tasks:
  - name: Show ver
    ios_command:
      commands: "show version"
    register: result
      
  - name: Display output
    debug: var=result.stdout_lines
