---
- name: run multiple commands on remote nodes 
  hosts: all
  gather_facts: no
  
  tasks:
    - name: show ver, show interfaces
    ios_command:
      commands:
      - show version
      - show interfaces
